plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude '**/.cache/**'
}

repositories {
    maven { url = 'https://maven.moddingx.org/' }
    maven { url = 'https://maven.blamejared.com/' }
    maven { url = 'https://maven.theillusivec4.top/releases/' }
    maven { url = 'https://modmaven.dev/' }
    maven { url = 'https://maven.shedaniel.me/' }
    maven { url = 'https://www.cursemaven.com' }
}

neoForge {
    version = neo_version

    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_mappings_version
    }

    accessTransformers = files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all',
                    '--output', file('src/generated/resources/').absolutePath,
                    '--existing', file('src/main/resources/').absolutePath
        }

        configureEach {
            logLevel = org.slf4j.event.Level.INFO
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    annotationProcessor "org.moddingx:LibX:${libx_version}"

    implementation "org.moddingx:LibX:${libx_version}"
    implementation "vazkii.botania:botania-neoforge-1.21.1:${botania_version}"
    implementation "vazkii.patchouli:Patchouli:${patchouli_version}"
    implementation "top.theillusivec4.curios:curios-neoforge:${curios_version}"

    compileOnly "mezz.jei:jei-1.21.1-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-1.21.1-neoforge-api:${jei_version}"
    localRuntime "mezz.jei:jei-1.21.1-neoforge:${jei_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version       : minecraft_version,
            minecraft_version_range : minecraft_version_range,
            neo_version             : neo_version,
            neo_version_range       : neo_version_range,
            loader_version_range    : loader_version_range,
            mod_id                  : mod_id,
            mod_name                : mod_name,
            mod_license             : mod_license,
            mod_version             : mod_version,
            mod_authors             : mod_authors,
            mod_description         : mod_description,
            libx_version_range      : libx_version_range,
            botania_version_range   : botania_version_range,
            patchouli_version_range : patchouli_version_range,
            curios_version_range    : curios_version_range,
            jei_version_range       : jei_version_range
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into layout.buildDirectory.dir('generated/sources/modMetadata')
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
