org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.233
neo_version_range=[21.1.233,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=mythicbotany
mod_name=MythicBotany
mod_license=APACHE-2.0
mod_version=5.0.0-neoforge-1.21.1
mod_group_id=de.melanx.mythicbotany
mod_authors=noeppi_noeppi, Contributors: MelanX
mod_description=Dive deeper into the world of botania.

libx_version=1.21.1-6.0.13
libx_version_range=[1.21.1-6.0.13,)
botania_version=454-20260618.183251-45
botania_version_range=[1.21.1-454,)
patchouli_version=1.21.1-92-NEOFORGE
patchouli_version_range=[1.21.1-92,)
curios_version=9.5.1+1.21.1
curios_version_range=[9.5.1+1.21.1,)
jei_version=19.27.0.340
jei_version_range=[19.27.0.340,)
